image: ubuntu:latest

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - |
            apt-get update && apt-get install -y maven openjdk-11-jdk
            mvn clean install --file Automation_Scripts/pom.xml
	    echo "script sucessfull"
            TEST_RESULT=$?
            echo $TEST_RESULT > test_result.txt

    - step:
        name: Create Jira Issue if Tests Fail
        script:
          - |
            TEST_RESULT=$(cat test_result.txt)
            if [ "$TEST_RESULT" -ne 0 ]; then
              echo "Tests failed, creating Jira issue."
              cat <<EOF > issue_payload.json
              {
                "fields": {
                  "project": {
                    "key": "$JIRA_PROJECT"
                  },
                  "summary": "Build Failure: $(date +'%Y-%m-%d %H:%M:%S')",
                  "description": "This issue is created from Bitbucket Pipelines. Please check the build logs for details.",
                  "issuetype": {
                    "name": "Bug"
                  }
                }
              }
              EOF
              curl -D- -u $JIRA_USER_EMAIL:$JIRA_API_TOKEN -X POST --data @issue_payload.json -H "Content-Type: application/json" $JIRA_BASE_URL/rest/api/2/issue/
            else
              echo "Tests passed, no Jira issue created."
            fi

    - step:
        name: Security Scan
        script:
          - |
            apt-get update && apt-get install -y git
            pipe: atlassian/git-secrets-scan:0.5.1
