image: maven:3.9.2

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean install --file Automation_Scripts/pom.xml || echo "Build failed" > build_status.txt
        after-script:
          - pipe: atlassian/checkstyle-report:0.3.0
          - >
            if [ -f build_status.txt ]; then
              JIRA_BASE_URL="${JIRA_BASE_URL}"
              JIRA_USER_EMAIL="${JIRA_USER_EMAIL}"
              JIRA_API_TOKEN="${JIRA_API_TOKEN}"
              JIRA_PROJECT="YOUR_PROJECT_KEY"
              JIRA_ISSUE_SUMMARY="Build Failure: $(date +'%Y-%m-%d %H:%M:%S')"
              JIRA_ISSUE_DESCRIPTION="The Bitbucket pipeline for the Maven project has failed. Please investigate the issue."

              pipe: atlassian/jira-create-issue:0.7.0
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                JIRA_PROJECT: $JIRA_PROJECT
                JIRA_ISSUE_TYPE: "Bug"
                
            else
              echo "Build succeeded, no Jira ticket created."
            fi
    - step:
        name: Security Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1
