image: maven:3.9.2

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - |
            # Run the build and tests
            mvn clean test --file Automation_Scripts/pom.xml || echo "Build Failed"
            BUILD_STATUS=$?

            # Run checkstyle regardless of build status
            pipe: atlassian/checkstyle-report:0.3.0

            # If build fails, create a Jira issue
            if [ $BUILD_STATUS -ne 0 ]; then
              pipe: atlassian/jira-create-issue:0.7.0
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                JIRA_PROJECT: $JIRA_PROJECT
                JIRA_ISSUE_TYPE: "Bug"
                JIRA_ISSUE_SUMMARY: "Build Failure Detected: $(date +'%Y-%m-%d %H:%M:%S')"
                JIRA_ISSUE_DESCRIPTION: "A build failure occurred in Bitbucket Pipelines."
            fi

            # Exit with the original build status
            exit $BUILD_STATUS

    - step:
        name: Security Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1
