# Template maven-build

# This template allows you to test and build your Java project with Maven.
# The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.9.2

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - maven
            script:
              - mvn clean install --file Automation_Scripts/pom.xml || echo "Build failed"
            after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
              - pipe: atlassian/checkstyle-report:0.3.0

        - step:
            name: Create Jira Issue on Failure
             script:
              - pipe: atlassian/jira-create-issue:0.7.0
                  variables:
                    JIRA_BASE_URL: $JIRA_BASE_URL
                    JIRA_USER_EMAIL: $JIRA_USER_EMAIL
    		    JIRA_API_TOKEN: $JIRA_API_TOKEN
     		    JIRA_PROJECT: "PROJ"
      		    JIRA_ISSUE_SUMMARY: "This is a sample issue summary"

        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
