name: Maven Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Test
        id: build
        run: |
          mvn clean install --file Automation_Scripts/pom.xml
        continue-on-error: true

      - name: Check Build Result
        id: build_result
        run: |
          if ($?) { echo "Build succeeded" } else { echo "Build failed"; exit 1 }

      - name: Run Checkstyle
        if: steps.build.outcome == 'success'
        run: |
          mvn checkstyle:checkstyle --file Automation_Scripts/pom.xml || echo "Checkstyle failed, but continuing..."

      - name: Checkstyle Report
        if: steps.build.outcome == 'success'
        uses: atlassian/checkstyle-report@v0.3.0

      - name: Create Jira Issue
        if: steps.build.outcome == 'failure'
        uses: atlassian/jira-create-issue@v0.7.0
        with:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT: ${{ secrets.JIRA_PROJECT }}
          JIRA_ISSUE_TYPE: "Bug"
          JIRA_ISSUE_SUMMARY: "Build Failure: ${{ github.event.head_commit.timestamp }}"
          JIRA_ISSUE_DESCRIPTION: "This issue is created from GitHub Actions."

      - name: Security Scan
        if: steps.build.outcome == 'success'
        uses: atlassian/git-secrets-scan@v0.5.1
