image: maven:3.9.2

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - chmod +x build_and_create_jira_issue.sh
          - ./build_and_create_jira_issue.sh

    - step:
        name: Security Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1
