# Template maven-build

# This template allows you to test and build your Java project with Maven.
# The workflow allows running tests, code checkstyle, and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.9.2

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean install --file Automation_Scripts/pom.xml
        after-script:
          - |
            if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then
              echo "Build failed"
              echo "Creating Jira issue..."
              export JIRA_ISSUE_SUMMARY="Build Failure: $(date +'%Y-%m-%d %H:%M:%S')"
              export JIRA_ISSUE_DESCRIPTION="This issue is created from Bitbucket Pipelines."
              curl -s -u $JIRA_USER_EMAIL:$JIRA_API_TOKEN -X POST -H "Content-Type: application/json" \
                   $JIRA_BASE_URL/rest/api/3/issue/ \
                   -d '{
                         "fields": {
                             "project": {
                                 "key": "'"$JIRA_PROJECT"'"
                             },
                             "summary": "'"$JIRA_ISSUE_SUMMARY"'",
                             "description": "'"$JIRA_ISSUE_DESCRIPTION"'",
                             "issuetype": {
                                 "name": "Bug"
                             }
                         }
                     }'
            fi

    - step:
        name: Security Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1
