image: maven:3.9.2

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - |
            # Run the build and tests
            mvn clean test --file Automation_Scripts/pom.xml
            BITBUCKET_EXIT_CODE=$?

            # Run checkstyle regardless of build status
            mvn checkstyle:checkstyle --file Automation_Scripts/pom.xml || echo "Checkstyle failed, but continuing..."
            pipe: atlassian/checkstyle-report:0.3.0

            # Exit with the original build status
            exit $BITBUCKET_EXIT_CODE

    - step:
        name: Create Jira Issue on Build Failure
        script:
          - |
            if [[ $BITBUCKET_EXIT_CODE -eq 0 ]]; then
              echo "Build succeeded, skipping Jira issue creation."
              exit 0
            else
              echo "Build failed, creating Jira issue."
              pipe: atlassian/jira-create-issue:0.7.0
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                JIRA_PROJECT: $JIRA_PROJECT
                JIRA_ISSUE_TYPE: "Bug"
                JIRA_ISSUE_SUMMARY: "Build Failure Detected: $(date +'%Y-%m-%d %H:%M:%S')"
                JIRA_ISSUE_DESCRIPTION: "A build failure occurred in Bitbucket Pipelines."
            fi
        services:
          - docker

    - step:
        name: Security Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1
