# Template maven-build

# This template allows you to test and build your Java project with Maven.
# The workflow allows running tests, code checkstyle, and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.9.2

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          
            mvn clean install --file Automation_Scripts/pom.xml 
     
       

  

    - step:
        name: Always Run Security Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1
