image: mcr.microsoft.com/windows/servercore:ltsc2019

pipelines:
  default:
    - step: &build-and-test
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean install --file Automation_Scripts/pom.xml || { echo "Build failed"; exit 1; }

    - step: &checkstyle
        name: Run Checkstyle
        script:
          - mvn checkstyle:checkstyle --file Automation_Scripts/pom.xml || echo "Checkstyle failed, but continuing..."
          - pipe: atlassian/checkstyle-report:0.3.0

    - step: &create-jira-issue
        name: Create Jira Issue
        script:
          - pipe: atlassian/jira-create-issue:0.7.0
            variables:
              JIRA_BASE_URL: $JIRA_BASE_URL
              JIRA_USER_EMAIL: $JIRA_USER_EMAIL
              JIRA_API_TOKEN: $JIRA_API_TOKEN
              JIRA_PROJECT: $JIRA_PROJECT
              JIRA_ISSUE_TYPE: "Bug"
              JIRA_ISSUE_SUMMARY: "Build Failure: $(date +'%Y-%m-%d %H:%M:%S')"
              JIRA_ISSUE_DESCRIPTION: "This issue is created from Bitbucket Pipelines."

    - step: &security-scan
        name: Security Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1

    - step:
        name: Build and Test
        <<: *build-and-test

    - step:
        name: Check Build Result
        script:
          - if (Test-Path "target\surefire-reports\*-failure.txt") { Write-Host "Build failed"; exit 1 } else { Write-Host "Build succeeded"; exit 0 }

    - step:
        name: Run Checkstyle
        <<: *checkstyle
        condition:
          changesets:
            includePaths:
              - target/s
