image: maven:3.9.2

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean test --file Automation_Scripts/pom.xml
        after-script:
         - if [[ BITBUCKET_EXIT_CODE -eq 0 ]]; then exit 0; else echo "Step failed" ; fi
          - echo "only execute this if step failed"


    - step:
        name: Security Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1
