# Template maven-build

# This template allows you to test and build your Java project with Maven.
# The workflow allows running tests, code checkstyle, and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.9.2

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean install --file Automation_Scripts/pom.xml || echo "Build failed" && exit 1
        after-script:
          - >
            mvn checkstyle:checkstyle --file Automation_Scripts/pom.xml
            || echo "Checkstyle failed, but continuing..."
    
    - step:
        name: Create Jira Issue
        script:
          - >
            if [ "$(cat /opt/atlassian/pipelines/agent/build/.bitbucket/pipelines/build_status)" -ne 0 ]; then
              pipe: atlassian/jira-create-issue:0.7.0
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                JIRA_PROJECT: $JIRA_PROJECT
                JIRA_ISSUE_SUMMARY: "Build Failed"
                JIRA_ISSUE_DESCRIPTION: "The build failed for commit ${BITBUCKET_COMMIT}. Check the pipeline logs for details."
            fi
        artifacts:
          - /opt/atlassian/pipelines/agent/build/.bitbucket/pipelines/build_status
    
    - step:
        name: Security Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1
