# Template maven-build

# This template allows you to test and build your Java project with Maven.
# The workflow allows running tests, code checkstyle, and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.9.2

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean install --file Automation_Scripts/pom.xml
        
        # After the script runs, check the exit code and conditionally create a Jira issue
        after-script:
          - |
            BUILD_EXIT_CODE=$?

            if [ "$BUILD_EXIT_CODE" -ne 0 ]; then
              echo "Build failed, creating Jira issue..."

              # Pipe to create Jira issue
              pipe: atlassian/jira-create-issue:0.7.0
              variables:
                JIRA_BASE_URL: $JIRA_BASE_URL
                JIRA_USER_EMAIL: $JIRA_USER_EMAIL
                JIRA_API_TOKEN: $JIRA_API_TOKEN
                JIRA_PROJECT: $JIRA_PROJECT
                JIRA_ISSUE_SUMMARY: "Build/Test Issue - Failed"
                JIRA_ISSUE_DESCRIPTION: "This issue is created from Bitbucket Pipelines because the build failed."
            else
              echo "Build succeeded, skipping Jira issue creation."
            fi

    - step:
        name: Security Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1
